export const ADD_STUDENT = "ADD_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const REMOVE_STUDENT = "REMOVE_STUDENT";

// get todo list
export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

// get information
export const GET_INFORMATION_REQUEST = "GET_INFORMATION_REQUEST";
export const GET_INFORMATION_SUCCESS = "GET_INFORMATION_SUCCESS";
export const GET_INFORMATION_FAILURE = "GET_INFORMATION_FAILURE";
